### ISSUE TITLE
add the ability to customize the hotkey

### ISSUE THREAD

**Issue by glyph** [sieren/WidgetToggler#4]
It'd be great to be able to interactively specify the shortcut to avoid conflicts with applications that might want to use ⌘⌃W for some other function, with a framework like https://github.com/cocoabits/MASShortcut .  (I know that one is archived, but I'm not sure what replaces it.)

**Comment by sieren** [comment]
@glyph Thanks!
Added that feature into version 1.2 which is now available here: https://github.com/sieren/WidgetToggler/releases/tag/1.2.0

**Comment by glyph** [comment]
> @glyph Thanks! Added that feature into version 1.2 which is now available here: https://github.com/sieren/WidgetToggler/releases/tag/1.2.0

Wow. Thank you!
